### ISSUE TITLE
[help wanted] PoC write about upload

### ISSUE THREAD

**Issue by kmahyyg** [chaitin/xray#1013]
Currently, since the PoC of xray is written in yaml which is a plain-text based file, I wonder if the http body in a rule of a PoC can use any internal function like `base64Decode()`, so that I could encode the binary into a text file and upload it in the http body.

keyword: `Content-Type: application/octet-stream`

**Comment by zema1** [comment]
发现你是国人，我就直接中文回复吧，免得表述不清。

我猜的你本意是想上传 bytes 的类型的 body，当前最新版本确实是实现不了，因为对 bytes 的处理有 bug，最近两天将会发布一个新版本解决这个问题。有一个相似问题的 poc 已经被我合了，可以参考下写法，这个 poc 需要在新版发布后才能按预期运行。

https://github.com/chaitin/xray/blob/master/pocs/yonyou-nc-arbitrary-file-upload.yml

更进一步的，当然也可以在 set 中使用一些函数来对变量进行解码之类的操作。一个理论的可行的例子是这样：

```yaml
name: poc-yaml-test-body-binary
set:
  r1: b"xxxxxxxx"
  b64Data: base64encode(r1)
rules:
  - method: POST
    path: /
    body: >-
      {{b64Data}}
    expression: |
      response.status == 200
```
