### ISSUE TITLE
How to update xray to latests github pocs

### ISSUE THREAD

**Issue by abdilahrf** [chaitin/xray#1095]
Hi,

I there is any way that i could update my xray to use the latests pocs from this github repository without waiting the next binary releases ?

**Comment by abdilahrf** [comment]
Is that will use the latest POC merged 1minutes ago?

**Comment by phith0n** [comment]
Hi there, 

Community POCs won't be integrated into X-Ray's binary until we are completely test them in the commercial environment, this can be take a long time.

But you can use community POCs yourselves, just pull this repository and specify glob rule in the config.yaml:

```yaml
#...
  phantasm:
    enabled: true
    depth: 1
    exclude_poc: []
    include_poc: 
    - /path/to/your/pocs/directory/*.yaml
# ...
```
