### ISSUE TITLE
反连平台 rmi_server failed to split path

### ISSUE THREAD

**Issue by LioTree** [chaitin/xray#1186]
使用以下代码测试

* RMI/RMIServer.java

```java
package RMI;

import java.rmi.Naming;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;

public class RMIServer{
    public interface IRemoteHelloWorld extends Remote{
        public String hello() throws RemoteException;
    }

    public class RemoteHelloWorld extends UnicastRemoteObject implements IRemoteHelloWorld{
        protected RemoteHelloWorld() throws RemoteException{
            super();
        }

        public String hello() throws RemoteException{
            System.out.println("call from");
            return "Hello world";
        }
    }
    private void start() throws Exception{
        RemoteHelloWorld h = new RemoteHelloWorld();
        LocateRegistry.createRegistry(1099);
        Naming.rebind("rmi://127.0.0.1:1099/Hello",h);
    }

    public static void main(String[] args) throws Exception{
        new RMIServer().start();
    }
}
```

* RMI/RMIClient.java

```java
package RMI;

import RMI.RMIServer;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

public class RMIClient{
    public static void main(String[] args) throws Exception {
        RMIServer.IRemoteHelloWorld hello = (RMIServer.IRemoteHelloWorld)
                Naming.lookup("rmi://127.0.0.1:1099/Hello");
        String ret = hello.hello();
        System.out.println(ret);
    }
}
```

RMI可以正常使用：

![image](https://user-images.githubusercontent.com/12847578/114882067-27516380-9e36-11eb-96e8-95e8cf23999e.png)

关闭RMIServer后使用xray反连平台测试，config.yaml reverse部分如下：

```yaml
reverse:
  db_file_path: "reverse.db"                      # 反连平台数据库文件位置, 这是一个 KV 数据库
  token: "123456"                             # 反连平台认证的 Token, 独立部署时不能为空
  http:
    enabled: true
    listen_ip: 127.0.0.1 
    listen_port: "1099"
    ip_header: ""                       # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
  dns:
    enabled: true
    listen_ip: 127.0.0.1
    domain: ""                          # DNS 域名配置
    is_domain_name_server: false        # 是否修改了域名的 ns 为反连平台，如果是，那 nslookup 等就不需要指定 dns 了
    resolve:                            # DNS 静态解析规则
    - type: A                           # A, AAAA, TXT 三种
      record: localhost
      value: 127.0.0.1
      ttl: 60
  client:
    remote_server: false                # 是否是独立的远程 server，如果是要在下面配置好远程的服务端地址
    http_base_url: ""                   # 默认将根据 ListenIP 和 ListenPort 生成，该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置
    dns_server_ip: ""                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址
```

运行RMIClient得到报错：

![image](https://user-images.githubusercontent.com/12847578/114882548-a3e44200-9e36-11eb-903a-97b704ef5d08.png)

![image](https://user-images.githubusercontent.com/12847578/114882512-9c249d80-9e36-11eb-972b-f66d08bf3566.png)

```
[ERRO] 2021-04-15 22:04:30 [reverse:rmi_server.go:154] failed to split path \x00\x02K\x00
172.25.176.1\x00\x00\x00\x00P\xac\xed\x00\x05w"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02D\x15M\xc9\xd4\xe6;\xdft\x00\x05Hello\x00
```

反连平台web界面无记录：

![image](https://user-images.githubusercontent.com/12847578/114882702-caa27880-9e36-11eb-9260-bfeaa18dae87.png)
