### ISSUE TITLE
https 双向校验，client的证书怎么给xray

### ISSUE THREAD

**Issue by lhtest429** [chaitin/xray#1290]
https 双向校验，client的证书怎么给xray

**Comment by virusdefender** [comment]
在配置文件的 `http` 那一段中增加

```yaml
http:
  proxy: "http://127.0.0.1:8080"
  # ........
  pkcs12:
    path: "xxx.p12"
    password: "xxx"
```
