### ISSUE TITLE
detect_sqli_in_cookie: false 还在扫描cookie注入

### ISSUE THREAD

**Issue by depycode** [chaitin/xray#1525]
请问为什么设置了 detect_sqli_in_cookie: false  ，还在往cookie里面插入注入poc，使用的 1.8.2版本
```
  sqldet:
    enabled: true
    boolean_based_detection: true       # 是否检测布尔盲注
    error_based_detection: true         # 是否检测报错注入
    time_based_detection: true          # 是否检测时间盲注
    use_comment_in_payload: false       # 在 payload 中使用 or, 慎用！可能导致删库！
    detect_sqli_in_cookie: false         # 是否检查在 cookie 中的注入
```
