### ISSUE TITLE
1.9.3 反连报错

### ISSUE THREAD

**Issue by zerokeeper** [chaitin/xray#1683]
使用的独立部署的反连平台，而且根本没有配置dns反连接，
`dns_server_ip: ""`
同样的配置文件再1.8版本没有报错，在这个版本每次运行都要不停的报错
`[ERRO] [runner client:reverse.go:20] got domain error, reverse/client config dns_server_ip is empty`

**Comment by Jarcis-cy** [comment]
按照这个文章看一下哪里不一样了？https://www.yuque.com/jarciscy/zkonow/ty8car?# 《如何部署xray反连平台》

**Comment by ViCrack** [comment]
我也遇到过这种情况，只开启了reverse.http，而reverse.dns 是enabled: false，还是一直报错 dns_server_ip is empty

**Comment by zerokeeper** [comment]
```
    dns_server_ip: "8.130.41.223"                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址
    # 如果没有准备启动dns，没有准备域名，请不要填写
```

是的，我也是设置的dns_server_ip: ""     之前1.8的版本使用起来就一直没问题

**Comment by Jarcis-cy** [comment]
能发一下客户端和服务端的配置文件吗？还有客户端和服务端都是最新版吗？我刚测试了一遍，并没有出现报错

**Comment by ViCrack** [comment]
@Jarcis-cy 

我刚刚又重试了一下，现在又没出现报错了

![图片](https://user-images.githubusercontent.com/18179821/201064933-c9bfe395-86ba-4d7b-a80c-927eab41b877.png)

![图片](https://user-images.githubusercontent.com/18179821/201065483-8c3abff7-fd2f-4d81-88f8-79102e4b2f4b.png)


有点奇怪，可能是我之前config写的有问题的，如果再遇到了我再发一次

**Comment by zerokeeper** [comment]
配置文件是按照默认或者文档里面的

服务端

```
reverse:
  db_file_path: "test.db"        # 反连平台数据库文件位置, 这是一个 KV 数据库
  token: "xxxxx"                      # 反连平台认证的 Token, 独立部署时不能为空
  http:
    enabled: true
    listen_ip: 0.0.0.0 
    listen_port: "8777"
    ip_header: ""                # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
  dns:
    enabled: false
    listen_ip: 0.0.0.0 
    domain: ""      # 此处填写刚才准备好的域名，如果没有准备启动dns，没有准备域名，请不要填写
    is_domain_name_server: false        # 是否修改了域名的 ns 为反连平台，如果是，那 nslookup 等就不需要指定 dns 了
    resolve:                            # DNS 静态解析规则
    - type: A                           # A, AAAA, TXT 三种
      record: localhost
      value: 127.0.0.1
      ttl: 60
  client:
    remote_server: false                # 是否是独立的远程 server，如果是要在下面配置好远程的服务端地址
    http_base_url: "http://test.com"                   # 默认将根据 ListenIP 和 ListenPort 生成，该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置
    dns_server_ip: ""                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址
    # 如果没有准备启动dns，没有准备域名，请不要填写
   ```

客服端

```
reverse:
  db_file_path: ""        # 反连平台数据库文件位置, 这是一个 KV 数据库
  token: "xxxxx"                      # 反连平台认证的 Token, 独立部署时不能为空
  http:
    enabled: false
    listen_ip: 0.0.0.0 
    listen_port: "8777"
    ip_header: ""                # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
  dns:
    enabled: false
    listen_ip: 0.0.0.0 
    domain: ""      # 此处填写刚才准备好的域名，如果没有准备启动dns，没有准备域名，请不要填写
    is_domain_name_server: true        # 是否修改了域名的 ns 为反连平台，如果是，那 nslookup 等就不需要指定 dns 了
    resolve:                            # DNS 静态解析规则
    - type: A                           # A, AAAA, TXT 三种
      record: localhost
      value: 127.0.0.1
      ttl: 60
  client:
    remote_server: true                # 是否是独立的远程 server，如果是要在下面配置好远程的服务端地址
    http_base_url: "http://test.com"                   # 默认将根据 ListenIP 和 ListenPort 生成，该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置
    dns_server_ip: ""                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址
    # 如果没有准备启动dns，没有准备域名，请不要填写

```
客服端和服务器程序版本是一致的


测试了下，单独用某个插件不会提示报错的，但是如果用爬虫启用全部插件扫描就会报错
xray webscan --poc poc-go-apache-log4j2-rce --basic http://example.com/
xray webscan --plugins fastjson  http://example.com/

[reverse:reverse.go:70] remote reverse server check passed



xray webscan --basic http://example.com/

[INFO] 2022-11-20 10:08:11 [reverse:reverse.go:70] remote reverse server check passed
[ERRO] 2022-11-20 10:08:15 [runner client:reverse.go:20] got domain error, reverse/client config dns_server_ip is empty

配置文件里面的domain和dns_server_ip调试几次也没有用，注释或者为空都不行。1，8的旧版本就不会报错
