### ISSUE TITLE
poc编写 read_timeout: 问题。

### ISSUE THREAD

**Issue by 123xiaoyi** [chaitin/xray#1726]
```
name: poc-yaml-*
transport: http
rules:
  r0:
    request:
      method: GET
      path: /
      follow_redirects: false
      headers:
        Content-Type: application/xml
      body: aaaa
      read_timeout: "40"
    expression: response.status == 200
expression: r0()
detail:
  author: test
  links:
    - https://aaaaaa
```
代码添加 read_timeout 就会显示报错，去掉就不会报错，这个怎么解决，POC要使用read_timeout:
