### ISSUE TITLE
exclude_dir: ["sourcemap/default"]  无效

### ISSUE THREAD

**Issue by lovelyjuice** [chaitin/xray#1748]
```
 dirscan:
    enabled: true
    depth: 1                            # 检测深度，定义 http://t.com/a/ 深度为 1, http://t.com/a 深度为 0
    dictionary: ""                      # 自定义检测字典, 配置后将与内置字典**合并**
    exclude_dir: ["sourcemap/default"]                     # 想要排除的内部的扫描category，例如["sensitive/crossdomain","system/key"]
```
即便如此，xray还是会将sourcemap/default的结果输出到报告中
