### ISSUE TITLE
关于 poc 编写疑问

### ISSUE THREAD

**Issue by kb-at-zero** [chaitin/xray#1795]
我想在被动模式下，使用正则匹配去将代理过来的请求包 body 中包含 uuid 格式的 uuid 值（就是单纯的值，body 其他内容不修改）替换成 abc/ccc/../cbd 形式，然后在响应包中匹配是否包含 abc/cbd，若包含即存在穿越漏洞。
那么我想请问在写 poc 的时候，如何去取 request.body 中的参数呢？感谢。

**Comment by Jarcis-cy** [comment]
写了一个简单的demo：
```yaml
name: poc-yaml-test
transport: http
set:
  rbody: string(request.body)
  uuid1: '"(?P<uuid1>[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12})".submatch(rbody)["uuid1"]'
  nbody: replaceAll(rbody, uuid1, "abc/ccc/../cbd")
rules:
  r0:
    request:
      method: GET
      path: /{{nbody}}
    expression: response.status == 200
expression: r0()
detail:
  author: test
```
获取到的请求body如下图：

![image](https://github.com/chaitin/xray/assets/39492464/2894835e-c154-45b1-8063-ed48bb1a62a6)

经过POC之后，就修改成了这样：

![image](https://github.com/chaitin/xray/assets/39492464/095f13fc-b0e6-4ef9-a32e-3a94a1758a58)

所以你可以根据你的需求修改这个demo
