### ISSUE TITLE
关于 poc 逻辑分支

### ISSUE THREAD

**Issue by hundan2020** [chaitin/xray#720]
讨论一下，是否有必要支持 poc 的逻辑分支，按现在对xray的了解，poc只能向下执行，遇到expression为false则退出

考虑一种特殊情况，某一个漏洞，需要发两个包，第一个包有三种情况，其中两种是漏洞存在
第二个包在漏洞存在的基础上，根据不同响应执行不同请求

如果没有逻辑分支，此时需要写两个poc，而两个poc最多需要请求四次才能验证漏洞是否存在，而且至少会请求两次

如果加入逻辑分支，则请求次数会降低为最少一次最多两次，在请求次数上产生了优化

其次则是符合了一个漏洞一个poc的原则，在poc提交上显得相对完善 

此外，对于逻辑分支而言，除了if switch的实现方法之外，实际上只需要支持三元表达式和expression赋值，就可以实现一个比较hack的逻辑分支，考虑下面的伪代码

```
expression: response == 200 && set(value = test1) || response == 201 && set(value = test2) || response == 202 && set(value = test3)
...
path: {{!! value == test1 ? '/param1' : (value == test2 ? '/prarm2' : '/param3') !!}}

```

这种实现方式在需要的请求数增加时，会显得混乱，因为没有明确的指出上上级，不过混乱的问题也可以通过动态赋值近似解决，比如设置流程路径为 `001` `011`等，但完整的分支逻辑也许是更好的解决方案

如有对poc流程理解不正确的，还请指正

**Comment by phith0n** [comment]
这个问题可以讨论，你提的这个方法显然会导致POC不可阅读，增加流程路径什么的，没有统一化的方法，不建议自己又发明一种语法来设置workflow，所以暂时没想到什么不脏的实现方法。

**Comment by virusdefender** [comment]
你的理解没太大问题，这是一个功能完备性和易用性的权衡，你其实提到了多个问题

1. 简单的逻辑分支，类似于 `test_1 && (test2_1 || test_2_2)`，这种现在确实是通过多个 poc 文件来实现的，我们有考虑在单个 poc 中加入`或`操作，但是现在因为 yaml 格式，没好看点的写法。
1. 复杂的逻辑分支，类似 `test_1 && (test2_1 || test_2_2) || (test3_1 || test3_2)` 等等，或者更复杂的，这些和问题1一样，很难在 yaml 中表达，这种我们觉得就不应该支持。
1. 请求之间加入赋值和运算语句，你的目的是用于上面的复杂逻辑分支，不支持的原因同问题2，写法和理解过于复杂。但是我们之前考虑过支持中间变量赋值和运算是为了满足另外一个需求，比如将第一个请求的 response 做一些处理（比如字符串处理哈希等）用于第二个请求，目前只能直接传递变量而不能做处理。

**Comment by hundan2020** [comment]
@phith0n @virusdefender 
考虑一种写法如下

为poc每个请求增加一个可选的name属性以兼容已有poc，
为poc增加可选的workflow属性，使用markdown扩展写法写流程，将markdown流程与请求的name属性对应，即可产生完整流程

有workflow的poc走workflow，没有workflow的poc顺序执行

可以实现判断甚至循环，死循环的问题可以再讨论，比如通过在poc中限定请求次数解决

我觉得这相对来说是一个可以考虑的方案

**Comment by virusdefender** [comment]
感觉还是太复杂了，还不如去支持 Python、js 等代码 poc 呢

**Comment by phith0n** [comment]
markdown扩展写法？这个怎么写流程？

不建议在现在POC的基础上增加复杂的逻辑，否则会变成一个无限追求图灵完备的悖论。如果要设计复杂的POC，可以使用一些解释性语言，比如lua，或者这种<https://github.com/google/starlark-go>

**Comment by virusdefender** [comment]
lua 还是算了吧，语法和库太简单

**Comment by kiang70** [comment]
支持python的POC吧。

**Comment by yywing** [comment]
最近在思考这个问题。
起因是想用类似 poc 的格式实现指纹探测， 但是类似 nmap 的规则中有 softmatch 的结构。画个图就是

![图片](https://user-images.githubusercontent.com/22928185/124278575-00731580-db79-11eb-89a8-c6012cae94ec.png)


虚线上面的可以理解是我需要的，下面的左半部分是我们支持的，加上右半部分就能支持我想要的，所以更改大概是

之前 poc 定义：

```golang
        // 这个可以看作是历史遗留
	Rules       []*Rule                `yaml:"rules"`
       // 这个支持了可以有多个分支
	Groups      map[string][]*Rule     `yaml:"groups"`
```

新的定义：

```golang
        Rules     map[string]*Rule                `yaml:"rules"`
        Expression  string           `yaml:"expression"`
```

rule 的 结果为 rule.expression 的 bool 值

原有的 rules 定义下兼容  `expression` 为 1 && 2

原有 groups 定义下兼容  `expression` 为 （1 && 2）|| ( 3&&4 )


在下面这个场景下，定义名为 1-5 的 rule，

第一步，满足 1 或者 2 进行第二步
第二步，满足 3 或者 4 进行第三步
第三步，满足 5 


上述 `expression` 为 （1  || 2）&& （3 || 4） && 5

**Comment by chinaykc** [comment]
也许可以是类似于如下形式的递归定义。

```yaml
name: test-poc
rules:
  - name: login
    method: POST
    path: "/login"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: username:admin&password:admin
    expression: response.status==200
  - name: doexp1
    method: POST
    path: "/danger-path1"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: something danger
    expression: reponse.body.bcontains(something danger)
  - name: doexp2
    rules:
      - name: login-another-path
        method: POST
        path: "/login2"
        headers:
          Content-Type: application/x-www-form-urlencoded
        body: username:admin&password:admin
        expression: response.status==200
      - name: doexp
        method: POST
        path: "/danger-path2"
        headers:
        Content-Type: application/x-www-form-urlencoded
        body: something danger
        expression: reponse.body.bcontains(something danger)
    expression: login-another-path && doexp
expression: login && ( doexp1 || doexp2 )
```
