### ISSUE TITLE
配置文件中指定从目录加载 PoC

### ISSUE THREAD

**Issue by imp0wd3r** [chaitin/xray#75]
之前提到的从指定目录加载 PoC （#41 ）在命令行端已经实现了，感谢大佬们。

现在的情况是在配置文件中以 glob 的形式指定 PoC 无法加载。

配置如下：

```yaml
  phantasm:
    enabled: true
    poc:
    #- poc-yaml-drupal-drupalgeddon2-rce
    #- poc-yaml-joomla-cve-2015-7297-sqli
    #- poc-yaml-joomla-cve-2017-8917-sqli
    #- poc-yaml-thinkphp5-controller-rce
    #- poc-yaml-thinkphp5023-method-rce
    #- poc-go-tomcat-put
    - E:\xray\poc\*
```

运行结果：

![xray-poc-from-config-dir-fail](https://user-images.githubusercontent.com/17606044/63480491-a3aa6c80-c4c4-11e9-93a3-bb3dfe2d585f.png)

可以看到从命令行指定`--poc`是可以的，但是配置文件中的配置未生效，希望这两部分可以同步，感谢。
