### ISSUE TITLE
Setting A record for the Root Domain

### ISSUE THREAD

**Issue by uBadRequest** [chaitin/xray#908]
How do I set the A record for the root domain in the config.yaml file?

Xray doesn't like me using the @ symbol for the record .... currently if I try to resolve the root domain, it doesn't resolve.

**Comment by zema1** [comment]
There is an exmaple in config.yaml. The `resolve` part is used to set dns records

```
reverse:
  db_file_path: "" 
  token: ""
  dns:
    enabled: true
    listen_ip: 0.0.0.0 
    domain: "" 
    is_domain_name_server: false
    resolve: 
    - type: A  # A,AAA,TXT
      record: localhost
      value: 127.0.0.1
      ttl: 60
```
