### ISSUE TITLE
关于自定义POC的问题

### ISSUE THREAD

**Issue by 0-error** [chaitin/xray#927]
类似于这样的规则

```
name: poc-yaml-sqlpattern
rules:
  - follow_redirects: true
     path: "/"
     expression: |
       request.url.query.contains("select")
```

请求参数中包含 “select” 却无法匹配到，是什么原因？ 同样，用 `r'.*(select|union).*'.matches(request.url.query) `这样正则的方式也无法匹配。

动机是搭配rad时，想匹配一些 含有比较有意思的参数 的请求重点看一下，但是尝试之后没法实现， 姿势不对么？
