### ISSUE TITLE
[Feature Request] multi-step PoC support

### ISSUE THREAD

**Issue by kmahyyg** [chaitin/xray#941]
I'm currently trying to write a PoC to xray. 

However, I found some operation might need two steps to check if the vulnerability exists. Since you've already implemented yaml parser, why not add a multi-step PoC support like GitHub WorkFlow?

And also, to implement this feature, you might need to change the from `rules.method` as `string` to `rules.methods` as `string[]`.

finally, it will look like this:

```yaml
name: poc-yaml-example-com
rules:
  job1:
    - methods: [GET, POST]     # Both GET and POST method used the same payload
      path: "/knock-the-door"
      expression: |
       response.status==200 && response.body.bcontains(b'DOOR IS OPEN')
  job2:
    - methods: [GET, POST]
      getbody: true      # if true, data in body will not be transformed to querystring.
      path: "/get-a-root"
      body: "xxxx"     # in POST, as body or detect according to Header; in GET, transform to querystring.
      expression: |
       response.status==200 && response.body.bcontains(b'ROOT USER')
detail:
  author: name(link)
  links: 
    - http://example.com
```

the workflow will like: (pseudo code)

```py

def mutate_request_by_rule(req, rule):
    <REDACTED>
    finish(other_rules_before_current_rule_in_queue)
    block() 
    nthread = create_new_thread()
    for jobs in rule:
         # make sure the job runs synchronously
         if response.expression meets requirement:
                 run(job)
                 continue(next_job)
         else:
                 stop()
    nthread.destroy()
    unblock()
    <REDACTED>

for rule in rules:
    newReq = mutate_request_by_rule(req, rule)
    response = send(newReq)
    if not check_response(response, rule):
        break
```
