### ISSUE TITLE
v1.4.5版本detect_xss_in_cookie: false选项未起作用

### ISSUE THREAD

**Issue by ohlinge** [chaitin/xray#942]
设置如：
```
  xss:
    enabled: true
    detect_xss_in_cookie: false          # 是否探测入口点在 cookie 中的 xss
    ie_feature: false                   # 是否扫描仅能在 ie 下利用的 xss
```

然而仍然会去扫描cookie中的xss
